# =============================================================================
# Full Production App Spec - Customer Signals Copilot
# =============================================================================
# Deploy this after verifying connectivity with the debug container.
#
# Prerequisites:
#   1. Managed services created (see scripts/create-managed-services.sh)
#   2. Debug container connectivity tests passed
#   3. GitHub Secrets configured:
#      - DIGITALOCEAN_ACCESS_TOKEN
#      - SPACES_ACCESS_KEY
#      - SPACES_SECRET_KEY
#      - GRADIENT_API_KEY
#
# Usage:
#   doctl apps create --spec .do/app.yaml
# =============================================================================

name: signals-copilot
region: syd1

# VPC Configuration - enables private network connectivity to managed databases
vpc:
  id: 20ccc9c3-2bad-40dc-9669-8d5ef784b765  # default-syd1

# =============================================================================
# Ingress Rules (path-based routing with path preservation)
# =============================================================================
# IMPORTANT: More specific paths must come before catch-all (/)
# preserve_path_prefix ensures /v1/metrics/overview → core-api receives /v1/metrics/overview
# =============================================================================

ingress:
  rules:
    # Ingest API routes
    - component:
        name: ingest-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /v1/events

    # Core API routes
    - component:
        name: core-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /v1/incidents

    - component:
        name: core-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /v1/search

    - component:
        name: core-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /v1/metrics

    - component:
        name: core-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /v1/ai

    # Health check (routed to ingest-api as entry point)
    - component:
        name: ingest-api
        preserve_path_prefix: true
      match:
        path:
          prefix: /healthz

    # Dashboard (catch-all - must be last)
    - component:
        name: dashboard
        preserve_path_prefix: true
      match:
        path:
          prefix: /

# =============================================================================
# HTTP Services
# =============================================================================

services:
  # -------------------------------------------------------------------------
  # Ingest API - Event ingestion endpoint
  # -------------------------------------------------------------------------
  - name: ingest-api
    dockerfile_path: services/ingest-api/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /healthz
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      # PostgreSQL - PUBLIC (bindable) + PRIVATE (VPC)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_PRIVATE_URL}
      # Kafka - PUBLIC (bindable) + PRIVATE (VPC)
      - key: KAFKA_BROKERS
        scope: RUN_TIME
        value: ${kafka.HOSTNAME}:${kafka.PORT}
      - key: KAFKA_PRIVATE_BROKERS
        scope: RUN_TIME
        type: SECRET
        value: ${KAFKA_PRIVATE_BROKERS}
      - key: KAFKA_USERNAME
        scope: RUN_TIME
        value: ${kafka.USERNAME}
      - key: KAFKA_PASSWORD
        scope: RUN_TIME
        value: ${kafka.PASSWORD}
      - key: KAFKA_CA_CERT
        scope: RUN_TIME
        value: ${kafka.CA_CERT}
      - key: KAFKA_TOPIC
        scope: RUN_TIME
        value: signals.raw.v1

  # -------------------------------------------------------------------------
  # Core API - Incidents and search endpoint
  # -------------------------------------------------------------------------
  - name: core-api
    dockerfile_path: services/core-api/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    http_port: 3001
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /healthz
      initial_delay_seconds: 10
      period_seconds: 10

    envs:
      # PostgreSQL - PUBLIC (bindable) + PRIVATE (VPC)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_PRIVATE_URL}
      # OpenSearch - PUBLIC (bindable) + PRIVATE (VPC)
      - key: OPENSEARCH_URL
        scope: RUN_TIME
        value: https://${search.USERNAME}:${search.PASSWORD}@${search.HOSTNAME}:${search.PORT}
      - key: OPENSEARCH_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${OPENSEARCH_PRIVATE_URL}

  # -------------------------------------------------------------------------
  # Dashboard - Next.js frontend
  # -------------------------------------------------------------------------
  - name: dashboard
    dockerfile_path: apps/dashboard/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    http_port: 3002
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /
      initial_delay_seconds: 15
      period_seconds: 10

    # No environment variables needed - dashboard uses relative URLs for API calls
    # which get routed to core-api via App Platform path-based routing

# =============================================================================
# Workers (no HTTP routes - background processors)
# =============================================================================

workers:
  # -------------------------------------------------------------------------
  # Indexer - Kafka consumer → OpenSearch
  # -------------------------------------------------------------------------
  - name: indexer
    dockerfile_path: services/indexer/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    envs:
      # Kafka - PUBLIC (bindable) + PRIVATE (VPC)
      - key: KAFKA_BROKERS
        scope: RUN_TIME
        value: ${kafka.HOSTNAME}:${kafka.PORT}
      - key: KAFKA_PRIVATE_BROKERS
        scope: RUN_TIME
        type: SECRET
        value: ${KAFKA_PRIVATE_BROKERS}
      - key: KAFKA_USERNAME
        scope: RUN_TIME
        value: ${kafka.USERNAME}
      - key: KAFKA_PASSWORD
        scope: RUN_TIME
        value: ${kafka.PASSWORD}
      - key: KAFKA_CA_CERT
        scope: RUN_TIME
        value: ${kafka.CA_CERT}
      - key: KAFKA_TOPIC
        scope: RUN_TIME
        value: signals.raw.v1
      - key: KAFKA_GROUP_ID
        scope: RUN_TIME
        value: indexer-group
      # OpenSearch - PUBLIC (bindable) + PRIVATE (VPC)
      - key: OPENSEARCH_URL
        scope: RUN_TIME
        value: https://${search.USERNAME}:${search.PASSWORD}@${search.HOSTNAME}:${search.PORT}
      - key: OPENSEARCH_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${OPENSEARCH_PRIVATE_URL}

  # -------------------------------------------------------------------------
  # Incident Engine - Kafka consumer → PostgreSQL (rules and incidents)
  # -------------------------------------------------------------------------
  - name: incident-engine
    dockerfile_path: services/incident-engine/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    envs:
      # PostgreSQL - PUBLIC (bindable) + PRIVATE (VPC)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_PRIVATE_URL}
      # Kafka - PUBLIC (bindable) + PRIVATE (VPC)
      - key: KAFKA_BROKERS
        scope: RUN_TIME
        value: ${kafka.HOSTNAME}:${kafka.PORT}
      - key: KAFKA_PRIVATE_BROKERS
        scope: RUN_TIME
        type: SECRET
        value: ${KAFKA_PRIVATE_BROKERS}
      - key: KAFKA_USERNAME
        scope: RUN_TIME
        value: ${kafka.USERNAME}
      - key: KAFKA_PASSWORD
        scope: RUN_TIME
        value: ${kafka.PASSWORD}
      - key: KAFKA_CA_CERT
        scope: RUN_TIME
        value: ${kafka.CA_CERT}
      - key: KAFKA_TOPIC
        scope: RUN_TIME
        value: signals.raw.v1
      - key: KAFKA_GROUP_ID
        scope: RUN_TIME
        value: incident-engine-group
      - key: KAFKA_AI_JOBS_TOPIC
        scope: RUN_TIME
        value: signals.ai.jobs.v1

  # -------------------------------------------------------------------------
  # AI Worker - Job processor → Gradient AI
  # -------------------------------------------------------------------------
  - name: ai-worker
    dockerfile_path: services/ai-worker/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    envs:
      # PostgreSQL - PUBLIC (bindable) + PRIVATE (VPC)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_PRIVATE_URL}
      # Kafka (for job notifications) - PUBLIC (bindable) + PRIVATE (VPC)
      - key: KAFKA_BROKERS
        scope: RUN_TIME
        value: ${kafka.HOSTNAME}:${kafka.PORT}
      - key: KAFKA_PRIVATE_BROKERS
        scope: RUN_TIME
        type: SECRET
        value: ${KAFKA_PRIVATE_BROKERS}
      - key: KAFKA_USERNAME
        scope: RUN_TIME
        value: ${kafka.USERNAME}
      - key: KAFKA_PASSWORD
        scope: RUN_TIME
        value: ${kafka.PASSWORD}
      - key: KAFKA_CA_CERT
        scope: RUN_TIME
        value: ${kafka.CA_CERT}
      - key: KAFKA_AI_JOBS_TOPIC
        scope: RUN_TIME
        value: signals.ai.jobs.v1
      - key: KAFKA_GROUP_ID
        scope: RUN_TIME
        value: ai-worker-group
      # Gradient AI (DigitalOcean Serverless Inference)
      - key: GRADIENT_BASE_URL
        scope: RUN_TIME
        value: https://inference.do-ai.run/v1
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${GRADIENT_API_KEY}
      - key: GRADIENT_MODEL
        scope: RUN_TIME
        value: llama3.3-70b-instruct

  # -------------------------------------------------------------------------
  # Traffic Generator - Continuous synthetic traffic for demos/testing
  # -------------------------------------------------------------------------
  - name: traffic-gen
    dockerfile_path: services/traffic-gen/Dockerfile
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main
      deploy_on_push: false  # GitHub Actions controls deployment

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Minimal resources needed

    envs:
      # Ingest API - PRIVATE URL for VPC communication
      - key: INGEST_API_PRIVATE_URL
        scope: RUN_TIME
        value: ${ingest-api.PRIVATE_URL}
      # API Key for authentication
      - key: API_KEY
        scope: RUN_TIME
        value: dev-api-key-12345
      # Enable/disable traffic generation
      - key: TRAFFIC_GEN_ENABLED
        scope: RUN_TIME
        value: "true"
      # Event interval (ms) - ~10 events/min
      - key: EVENT_INTERVAL_MS
        scope: RUN_TIME
        value: "6000"
      # Error interval (ms) - 1 error every 5-10 min
      - key: ERROR_INTERVAL_MS
        scope: RUN_TIME
        value: "420000"
      # Environment tag for generated events
      - key: EVENT_ENVIRONMENT
        scope: RUN_TIME
        value: prod

# =============================================================================
# Managed Databases (Bindable Variables)
# =============================================================================
# IMPORTANT: These clusters must be created BEFORE deploying this app spec.
# See scripts/create-managed-services.sh
# =============================================================================

databases:
  # PostgreSQL
  - name: db
    engine: PG
    production: true
    cluster_name: signals-postgres
    db_name: signals_app
    db_user: signals_user

  # Kafka (NO trusted sources support)
  - name: kafka
    engine: KAFKA
    production: true
    cluster_name: signals-kafka

  # OpenSearch
  - name: search
    engine: OPENSEARCH
    production: true
    cluster_name: signals-opensearch
    db_user: signals_user

# =============================================================================
# Jobs (one-time or scheduled tasks)
# =============================================================================

jobs:
  # Database migrations (runs before deploy)
  - name: db-migrate
    dockerfile_path: db/Dockerfile.migrate
    github:
      repo: bikramkgupta/customer-signals-copilot
      branch: main

    instance_size_slug: apps-s-1vcpu-0.5gb
    kind: PRE_DEPLOY

    envs:
      # PostgreSQL - PUBLIC (bindable) + PRIVATE (VPC)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_PRIVATE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_PRIVATE_URL}
